package com.whatsbird.species

/**
 * One identifiable species, positioned by [index] which is the *class index* produced by the
 * bundled classifier. The order of [SpeciesDictionary.classes] is therefore load-bearing: it must
 * match the class order the model was trained with.
 */
data class Species(
    val index: Int,
    val scientificName: String,
    val englishName: String,
    val chineseName: String,
) {
    /** Chinese is the primary label for this app; English is the fallback for non-zh locales. */
    fun displayName(useChinese: Boolean): String =
        if (useChinese) chineseName else englishName
}

/** Everything the runtime needs to keep the model's output space and the app's UI in sync. */
data class SpeciesDictionary(
    val version: String,
    val modelVersion: String,
    val inputSize: Int,
    val inputScale: Float,
    val inputOffset: Float,
    val cropPaddingRatio: Float,
    val backgroundClassIndex: Int,
    val classes: List<Species>,
) {
    val classCount: Int get() = classes.size

    fun speciesAt(classIndex: Int): Species? =
        classes.firstOrNull { it.index == classIndex }

    val isEmpty: Boolean get() = classes.isEmpty()

    companion object {
        /**
         * The shipped asset is generated by `ml/export_assets.py` alongside the classifier, so the
         * two can never drift. If parsing fails the caller falls back to detection-only mode.
         */
        const val ASSET_PATH = "models/species.json"
    }
}
