/*
 * Copyright 2026 gongfpp (https://github.com/gongfpp/whatsBird)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.whatsbird.species

import android.content.Context
import org.json.JSONObject

/**
 * Loads `assets/models/species.json`. Deliberately tolerant: a missing or malformed dictionary
 * degrades the app to detection-only instead of crashing it.
 */
object SpeciesDictionaryLoader {

    /**
     * The shipped asset is generated by `ml/export_assets.py` alongside the classifier, so the
     * two can never drift. If parsing fails the caller falls back to detection-only mode.
     */
    private const val ASSET_PATH = "models/species.json"

    fun load(context: Context): SpeciesDictionary? {
        val raw = runCatching {
            context.assets.open(ASSET_PATH).bufferedReader(Charsets.UTF_8).use { it.readText() }
        }.getOrNull() ?: return null

        return runCatching { parse(raw) }.getOrNull()
    }

    private fun parse(raw: String): SpeciesDictionary {
        val root = JSONObject(raw)
        val array = root.optJSONArray("classes") ?: return empty()
        val classes = ArrayList<Species>(array.length())
        for (i in 0 until array.length()) {
            val item = array.getJSONObject(i)
            classes += Species(
                index = item.optInt("i", i),
                scientificName = item.optString("sci"),
                englishName = item.optString("en"),
                chineseName = item.optString("zh"),
            )
        }
        return SpeciesDictionary(
            modelVersion = root.optString("modelVersion", "unknown"),
            inputSize = root.optInt("inputSize", 224),
            inputScale = root.optDouble("inputScale", 1.0 / 127.5).toFloat(),
            inputOffset = root.optDouble("inputOffset", -1.0).toFloat(),
            cropPaddingRatio = root.optDouble("cropPaddingRatio", 0.15).toFloat(),
            backgroundClassIndex = root.optInt("backgroundClassIndex", -1),
            classes = classes,
        )
    }

    private fun empty() = SpeciesDictionary(
        modelVersion = "none",
        inputSize = 224,
        inputScale = 1f / 127.5f,
        inputOffset = -1f,
        cropPaddingRatio = 0.15f,
        backgroundClassIndex = -1,
        classes = emptyList(),
    )
}
