/*
 * Copyright 2026 gongfpp (https://github.com/gongfpp/whatsBird)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.whatsbird.species

/**
 * One identifiable species, positioned by [index] which is the *class index* produced by the
 * bundled classifier. The order of [SpeciesDictionary.classes] is therefore load-bearing: it must
 * match the class order the model was trained with.
 */
data class Species(
    val index: Int,
    val scientificName: String,
    val englishName: String,
    val chineseName: String,
)

/** Everything the runtime needs to keep the model's output space and the app's UI in sync. */
data class SpeciesDictionary(
    val modelVersion: String,
    val inputSize: Int,
    val inputScale: Float,
    val inputOffset: Float,
    val cropPaddingRatio: Float,
    val backgroundClassIndex: Int,
    val classes: List<Species>,
) {
    val classCount: Int get() = classes.size

    fun speciesAt(classIndex: Int): Species? =
        classes.firstOrNull { it.index == classIndex }

    val isEmpty: Boolean get() = classes.isEmpty()

    companion object {
        /**
         * The shipped asset is generated by `ml/export_assets.py` alongside the classifier, so the
         * two can never drift. If parsing fails the caller falls back to detection-only mode.
         */
        const val ASSET_PATH = "models/species.json"
    }
}
